CREATE TABLE IF NOT EXISTS heartbeat_store
(
    id UInt64 CODEC(Delta(8), LZ4),
    user_id UInt64 CODEC(T64, ZSTD(1)),
    time Float64 CODEC(Gorilla, ZSTD(1)),
    project Nullable(String) CODEC(ZSTD(3)),
    branch Nullable(String) CODEC(ZSTD(3)),
    entity Nullable(String) CODEC(ZSTD(3)),
    category LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    editor LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    language LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    machine LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    operating_system LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    type LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    user_agent Nullable(String) CODEC(ZSTD(3)),
    ip_address Nullable(String) CODEC(ZSTD(1)),
    dependencies Array(String) CODEC(ZSTD(3)),
    dependencies_is_null Bool DEFAULT false CODEC(ZSTD(1)),
    dependencies_json Nullable(String) CODEC(ZSTD(3)),
    lineno Nullable(Int32) CODEC(T64, ZSTD(1)),
    lines Nullable(Int32) CODEC(T64, ZSTD(1)),
    cursorpos Nullable(Int32) CODEC(T64, ZSTD(1)),
    line_additions Nullable(Int32) CODEC(T64, ZSTD(1)),
    line_deletions Nullable(Int32) CODEC(T64, ZSTD(1)),
    project_root_count Nullable(Int32) CODEC(T64, ZSTD(1)),
    is_write Nullable(Bool) CODEC(ZSTD(1)),
    source_type UInt8 CODEC(T64, ZSTD(1)),
    ysws_program UInt8 DEFAULT 0 CODEC(T64, ZSTD(1)),
    ja4_id Nullable(UInt64) CODEC(T64, ZSTD(1)),
    ai_model Nullable(String) CODEC(ZSTD(3)),
    ai_session Nullable(String) CODEC(ZSTD(3)),
    ai_subscription_plan LowCardinality(Nullable(String)) CODEC(ZSTD(1)),
    ai_input_tokens Nullable(Int64) CODEC(T64, ZSTD(1)),
    ai_output_tokens Nullable(Int64) CODEC(T64, ZSTD(1)),
    ai_prompt_length Nullable(Int32) CODEC(T64, ZSTD(1)),
    ai_line_changes Nullable(Int32) CODEC(T64, ZSTD(1)),
    human_line_changes Nullable(Int32) CODEC(T64, ZSTD(1)),
    deleted_at Nullable(DateTime64(6, 'UTC')) CODEC(Delta(8), ZSTD(1)),
    created_at DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    updated_at DateTime64(6, 'UTC') CODEC(Delta(8), ZSTD(1)),
    version UInt64 CODEC(T64, ZSTD(1)),
    fields_hash FixedString(32) CODEC(ZSTD(1)),
    alias_hashes Array(FixedString(32)) CODEC(ZSTD(1)),
    payload_hash FixedString(64) CODEC(ZSTD(1)),
    canonicalized Bool DEFAULT false CODEC(ZSTD(1)),
    duplicate_of Nullable(UInt64) CODEC(T64, ZSTD(1)),
    ja4_nullification_version UInt64 DEFAULT 0 CODEC(T64, ZSTD(1)),
    heartbeats_version UInt64 DEFAULT 0 CODEC(T64, ZSTD(1)),
    heartbeats_by_time_version UInt64 DEFAULT 0 CODEC(T64, ZSTD(1)),
    store_version UInt64 CODEC(T64, ZSTD(1)),
    INDEX fields_hash_lookup fields_hash TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX alias_hashes_lookup alias_hashes TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX ja4_id_lookup ja4_id TYPE bloom_filter(0.001) GRANULARITY 1
)
ENGINE = ReplacingMergeTree(store_version)
PARTITION BY toYYYYMM(created_at)
PRIMARY KEY (user_id, id)
ORDER BY (user_id, id)
SETTINGS index_granularity = 8192
