# Custom language definitions for Hackatime.
# Entries here take priority over config/languages.yml.

Lapse:
  type: programming
  color: "#C850C0"
  tm_scope: none
  ace_mode: text
  language_id: 999900001

GDScript3:
  type: programming
  color: "#488DBF"
  tm_scope: source.gdscript
  ace_mode: text
  language_id: 999900002

AsciiDoc:
  extensions:
  - ".ad"
