---
# The authentication token for the application.
authentication: <%= ENV["SKYLIGHT_AUTH_TOKEN"] %>
disable_dev_warning: true
ignored_endpoints:
  - SessionsController#impersonate
  - SessionsController#stop_impersonating
  - LetterOpenerWeb::Engine
  - Rails::HealthController#show
  - ActionDispatch::Routing::RouteSet#*
  - ActionDispatch::Static
